[package]
name = "bevy-rts-selection"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"
bevy_mod_raycast = "0.13"
bevy_panorbit_camera = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package.bevy]
opt-level = 3
